project:
  type: website

website:
  title: "rdgandhi22.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About .qmd
      - EPPS 6302.qmd
      - EPPS 6356.qmd
      - Resume.qmd

format:
  html:
    grid: 
      sidebar-width: 300px
      body-width: 650px
      margin-width: 450px
    theme: flatly 
    css: custom.css
    toc: true

editor: visual

