---
title: "Resume"
---

RICHA GANDHI 

richagandhi167\@gmail.com \| (214) 649-6004 \| The University of Texas at Dallas \| Bachelor of Science in International Political Economy\| Fast Track Master’s Program in Data Analytics and Research (B.S)

WORK EXPERIENCE: **UTD Student Working Group Program**— Undergraduate Researcher; Plano, TX August 2024 - Present• Transcribing/quantifying campaign finance reports and designing a class activity teaching students about social network analysis• Follow a data codebook to code information from PDFs about recipient of donation, amount contributed, and who the donor is• Developing an activity that teaches students how to understand and visualize the structure of campaign finance networks. 

**PKH Enterprises**— Research Specialist; Washington, DC June 2024  - August 2024 • Worked on research projects regarding topics with AI, cybersecurity, and its integration in the federal space • Found connections between federal use of perception analysis, implications of social media in policing, emotion sentiment analysis, and citizens trust of federal agencies due to AI’s impact and presented my findings to the company at the end of the internship • Analysis on data from various policy issues that have proposed changes or already existing ones 

**The Fund For American Studies Program**— Public Policy & Economics Student; Washington, DC June 2024 - August 2024 • Participated in the Public Policy + Economics Program track in The Fund for American Studies Academic Internship Program • Studied international economics and public policy through courses at George Mason University • Attended briefings at the U.S. capital and lead group discussions at think tanks and DC policy groups

LEADERSHIP EXPERIENCES: **Free The Facts**— Ambassador; August 2024 - Present • Working directly with FtF staff to produce events, grow engagement, spread awareness, and foster discussions on complex policy issues• Participating in exclusive events that delve into global issues of Social Security, Medicare, and student loans while networking with policy experts

**Microsoft Ambassador Program**— Ambassador; August 2024 - Present • Earn certification from Microsoft and the Office of Information Technology from building professionals and tools taught in the program if training, group work sessions, and meetings are successfully done• Present 3-5 ways how Microsoft products work together and share benefits of integration to a panel

**Amnesty International**— Membership Engagement Coordinator; January 2024 - May 2024 • Focusing on enhancing and maintaining member engagement and participation• Plan member specific events, workshops, and training sessions to keep members informed and motivated, collect feedback from members and implement strategies for improving their experience within the chapter• Human rights organization puts efforts in educational initiatives, protests and demonstrations, letter writing campaigns, awareness campaigns, advocacy, community outreach, research and reporting, and solidarity actions

**Partners In Health Engage**— Marketing Chair & Community Building Lead November 2022 - January 2024 • Worked with a network of teams around the U.S. to advance the movement of universal health care •Aimed to bring attention to global disparity in access to healthcare and push for global change by fundraising for the Butaro District Hospital and seasonal fundraisers held on campus• Taught students how to contact their representatives and hold informational congressional meeting workshops•Created newsletter for PIHE at UTD and graphics for meetings and events 

**Period Project**— Advocacy Director January 2022 - December 2023 • Worked with administration to plan out implementing free menstrual product dispensers in campus bathrooms •Worked with service team to put on events and incorporating education on topics relating to menstrual equity and women's rights as a whole 

 AWARDS AND SKILLS: 

**Awards and Honors:** TFAS Scholar, Toyota Making Life Easier recipient, Betty Ray Award, and AES Scholarship

**Intercultural Experience:** Study Abroad in Lugano, Switzerland; Franklin University June 2023-July2023 • Studied the death penalty, the law, public policy, and Civil liberties and the Criminal Process in the European Union

**Certifications:** Microsoft Certification,Introduction to Data Analytics-IBM Coursera, Excel for Data Analytics-IBM Coursera, HSP Social and Behavioral-CITI Program

**Software:** MS Word, PowerPoint, Excel, OneNote, Outlook, Canva
